// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var Battery0BarOutlinedIconThemed = NewThemedResource(Battery0BarOutlinedIconDarkRes, Battery0BarOutlinedIconLightRes)

var Battery0BarOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "battery_0_bar_outlined_dark.svg",
	StaticContent: []byte("<svg fill=\"#ffffff\" xmlns=\"http://www.w3.org/2000/svg\" enable-background=\"new 0 0 24 24\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\"><g><rect fill=\"none\" height=\"24\" width=\"24\"/></g><g><path d=\"M17,5v16c0,0.55-0.45,1-1,1H8c-0.55,0-1-0.45-1-1V5c0-0.55,0.45-1,1-1h2V2h4v2h2C16.55,4,17,4.45,17,5z M15,6H9v14h6V6z\"/></g></svg>"),
}

var Battery0BarOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "battery_0_bar_outlined_light.svg",
	StaticContent: []byte("<svg xmlns=\"http://www.w3.org/2000/svg\" enable-background=\"new 0 0 24 24\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\"><g><rect fill=\"none\" height=\"24\" width=\"24\"/></g><g><path d=\"M17,5v16c0,0.55-0.45,1-1,1H8c-0.55,0-1-0.45-1-1V5c0-0.55,0.45-1,1-1h2V2h4v2h2C16.55,4,17,4.45,17,5z M15,6H9v14h6V6z\"/></g></svg>"),
}
