// auto-generated
// Code generated by 'fynematic'. DO NOT EDIT.

package icon

import "fyne.io/fyne/v2"

var BatteryFullOutlinedIconThemed = NewThemedResource(BatteryFullOutlinedIconDarkRes, BatteryFullOutlinedIconLightRes)

var BatteryFullOutlinedIconDarkRes = &fyne.StaticResource{
	StaticName:    "battery_full_outlined_dark.svg",
	StaticContent: []byte("<svg fill=\"#ffffff\" xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\"><path d=\"M0 0h24v24H0V0z\" fill=\"none\"/><path d=\"M15.67 4H14V2h-4v2H8.33C7.6 4 7 4.6 7 5.33v15.33C7 21.4 7.6 22 8.33 22h7.33c.74 0 1.34-.6 1.34-1.33V5.33C17 4.6 16.4 4 15.67 4z\"/></svg>"),
}

var BatteryFullOutlinedIconLightRes = &fyne.StaticResource{
	StaticName:    "battery_full_outlined_light.svg",
	StaticContent: []byte("<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\"><path d=\"M0 0h24v24H0V0z\" fill=\"none\"/><path d=\"M15.67 4H14V2h-4v2H8.33C7.6 4 7 4.6 7 5.33v15.33C7 21.4 7.6 22 8.33 22h7.33c.74 0 1.34-.6 1.34-1.33V5.33C17 4.6 16.4 4 15.67 4z\"/></svg>"),
}
